
			<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
		<html><head>
      <!-- <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> -->
   <title>Creating an eBay Password</title><script language="JavaScript"><!--
includeHost='http://include.ebaystatic.com/';
//--></script><script src="http://include.ebaystatic.com/js/v/in/ebaybase.js"></script><script src="http://include.ebaystatic.com/js/v/in/ebaysup.js"></script><script type="text/javascript" language="JavaScript1.1">ebay.oDocument._getControl("headerCommon")._exec("writeStyleSheet");</script><script src="http://include.ebaystatic.com/js/v/in/features/help/contextual.js"></script><!--#en-IN#prod#ebay.com###help/new/contextual/create_password.html#STANDARD###Help.Contextual.create-password###ebay#UTF-8#--><script language="javascript" type="text/javascript">				
			var ieBackCompat=false; 
			if(document.compatMode&&document.compatMode!="BackCompat") ieBackCompat=true;
			var css='<link rel="stylesheet" href="http://include.ebaystatic.com/css/v/in/help/help';
			
				if(ebay.oGlobals.oClient.bNav||ebay.oGlobals.oClient.bFirefox||((typeof(usrCnt) != "undefined")?(ieBackCompat&&usrCnt):false))css+='-ns';
			
			css+='.css" type="text/css"/>';
			document.write(css);			
		</script><noscript><link rel="stylesheet" href="http://include.ebaystatic.com/css/v/in/help/help.css" type="text/css"></noscript></head><body bgcolor="#FFFFCC" topmargin="0" leftmargin="0" bottommargin="0" marginwidth="0" marginheight="0"><span class="navigation"></span><table border="0" width="100%" cellpadding="0" cellspacing="10"><tr><div id="areaTitle" style="background:url() no-repeat left top;background-color: #FFCC00; border-color: #FF9900;"><h1 style="white-space: nowrap;color:#000000">Help</h1><div style="background-image: url(http://pics.ebaystatic.com/aw/pics/areaTitles/atHelp.gif); overflow:hidden;"></div></div></tr><tr><td width="100%"><span class="pagetitle">Creating an eBay Password</span><p style="">You sign into your eBay account with your user ID and password. When creating your password, follow these tips:</p><p style="margin-bottom: 0px;"><b>Your password must be:</b></p><ul style="margin-top: 6px;"><li class="unorderedList"><div style="padding-left:4px;"><p style="">At least 6 characters</p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">A combination of <b>at least two</b> of the following: uppercase or lower case letters (A-Z or a-z), numbers (0-9) and special characters (?_!@#) (example: Cricketfan#28, $uperman1963)</p></div></li></ul><p style="margin-bottom: 0px;"><b>Your password can't be:</b></p><ul style="margin-top: 6px;"><li class="unorderedList"><div style="padding-left:4px;"><p style="">
                         Similar to your email address or eBay user ID. </p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">Common passwords or passwords with number or letter sequences (example: abc123, password2)</p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">Single words that can be found in the dictionary (example: kangaroo)</p></div></li></ul><div style=""><b>Other password tips:</b>
                <ul style="margin-top: 6px;"><li class="unorderedList"><div style="padding-left:4px;"><p style="">Don't use personal information that others can easily obtain or guess (example: your name, phone number, or birth date).</p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">The longer and more complex your password is, the harder it will be to guess. Place numbers and punctuation randomly in your password. </p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">Create a password that's secure, but still easy for you to remember. To help you remember your password, consider using a phrase or song title as your password. For example, "Somewhere Over the Rainbow" can become "Sw0tR8nBo."</p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">After creating your password, <b>protect it</b>. Don't share your password with others. </p></div></li><li class="unorderedList"><div style="padding-left:4px;"><p style="">Don't use the same password for your other online accounts, such as email, bank, and social networking accounts.</p></div></li></ul>
                <p style=""><b>Note: </b>eBay will never ask you to provide your password by email.</p></div><br><br></td><td width="10"><img src="http://pics.ebaystatic.com/aw/pics/x.gif" width="10" height="1"></td></tr><tr><td background="http://pics.ebaystatic.com/aw/pics/help/inline/dot_10x2.gif" colspan="3" height="2"><img src="http://pics.ebaystatic.com/aw/pics/x.gif" width="1" height="1"></td></tr><tr><td colspan="3"><br><br><input type="submit" name="Close" value="Close Window" onClick="javascript:window.close();"></td></tr></table><script language="JavaScript"><!--
				var isXconPage = "This is an xCon page\n" + "asset id: Help.Contextual.create-password" + "\n";
				//--></script><!--Page type : --><script src="http://include.ebaystatic.com/js/v/in/ebayfooter.js"></script><!--3/26/12 8:07 AM### buildId:14662364-->
<img style="display:none" width="1" height="1" alt="" title="" src="http://rover.ebay.in/roverimp/0/0/9?imp=1034826"/>
</body></html>
