use ebay;
INSERT INTO address (USER_ID,ADDRESS_TYPE,ADD1,ADD2,CITY,PIN,STATE,COUNTRY) VALUES ('MT2012119','P','E-city','Hosur road','Bangalore','560100','Karnataka','India');
INSERT INTO address (USER_ID,ADDRESS_TYPE,ADD1,ADD2,CITY,PIN,STATE,COUNTRY) VALUES ('MT2012122','P','electronic city','dfasdf','bangalore','32423','Karnataka','India');
INSERT INTO address (USER_ID,ADDRESS_TYPE,ADD1,ADD2,CITY,PIN,STATE,COUNTRY) VALUES ('MT2012140','RESIDENCE','electronic city','','bangalore','43434343','Karnataka','India');




INSERT INTO bank_acct (ACCOUNT_ID,ACCOUNT_NO,CARD_NO,CVV_NO,ACC_HOLDER_NAME,ACC_PWD,ACC_BAL,BANK_NAME,BRANCH_NAME,USER_ID) VALUES (1,1234,'1234567891234567',123,'Ruchika','OM',999190,'SBI','E-city','MT2012119');


INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (1,1,'MT2012013',2);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (2,4,'MT2012013',3);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (3,5,'MT2012013',1);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (5,3,'MT2012122',2);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (6,4,'MT2012122',2);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (7,1,'MT2012129',3);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (8,3,'MT2012129',2);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (9,4,'MT2012129',4);
INSERT INTO cart (CART_ID,ITEM_ID,USER_ID,ITEM_QUANTITY) VALUES (10,1,'MT2012119',89);


INSERT INTO category (CATEG_ID,CATEG_NAME) VALUES (1,'Books and Magazines');
INSERT INTO category (CATEG_ID,CATEG_NAME) VALUES (3,'Cosmetics');
INSERT INTO category (CATEG_ID,CATEG_NAME) VALUES (2,'Mobile Phones');


INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (1,'Author','Ulman Hopcroft');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (1,'Edition','2nd Edition');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (1,'Publisher','Pearson Publisher');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (2,'Author','Tanenbaum');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (2,'Edition','3rd Edition');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (2,'Publisher','Alchen Publisher');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (3,'Model','Samsung Mobile');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (3,'Store','Sangeetha Mobiles');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (4,'Model','Nokia SlideMobile');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (4,'Store','Spice Mobiles');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (5,'Author','Galvin');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (5,'Edition','2nd Edition');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (5,'Publisher','OS Publisher');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (6,'Author','Galvin');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (6,'Edition','2nd Edition');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (6,'Publisher','OS Publisher');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (7,'Author','Galvin');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (7,'Edition','2nd Edition');
INSERT INTO item_description (ITEM_ID,ATTRIBUTE,VALUE) VALUES (7,'Publisher','OS Publisher');

INSERT INTO list (LIST_ID,LIST_NAME,ITEM_ID,USERID) VALUES (2,'watchlist',2,'MT2012122');
INSERT INTO list (LIST_ID,LIST_NAME,ITEM_ID,USERID) VALUES (3,'watchlist',6,'MT2012122');


INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (1,'MT201212','2013-04-04 16:19:56',150);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (2,'MT2012122','2013-04-04 16:19:56',200);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (3,'MT2012129','2013-04-04 16:19:56',300);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (4,'MT2012122','2013-04-04 16:19:56',450);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (5,'MT2012122','2013-04-04 16:19:56',100);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (6,'MT2012119','2013-04-04 19:14:15',405);
INSERT INTO order_details (ORDER_ID,BUYER_ID,ORDER_DATE,TOTAL_PRICE) VALUES (7,'MT2012119','2013-04-04 19:28:56',405);



INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (1,'MT2012129','Introduction to Automata Theory',405,10,'New',8,'ModernOS.jpg',1,1,'DTDC',2);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (2,'MT2012129','Modern Operting System',600,30,'New',20,'Automata.jpg',1,2,'DTDC',3);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (3,'MT2012122','Samsung Galaxy Duos S 7562',7500,20,'New',5,'samsung.jpg',2,3,'Proffessional',5);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (4,'MT2012122','Nokia C203',3500,0,'New',15,'nokia.jpg',2,4,'Professional',6);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (5,'MT2012129','Design of Operting System',300,50,'New',12,'DesignOS.jpg',1,2,'DTDC',7);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (6,'MT2012129','Design of Operting System',300,60,'New',12,'DesignOS.jpg',1,2,'DTDC',7);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (7,'MT2012129','Design of Operting System',300,70,'New',12,'DesignOS.jpg',1,2,'DTDC',7);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (10,'MT2012129','Genuine weekend for woman',1300,10,'New',12,'perfume2.jpg',3,5,'DTDC',7);
INSERT INTO sell_item (ITEM_ID,USER_ID,ITEM_NAME,ITEM_PRICE,ITEM_DISCOUNT,ITEM_CONDITION,STOCK,ITEM_IMAGE,CATEG_ID,SUB_CATEG_ID,COURIER,SLA) VALUES (11,'MT2012129','Blue Fragrance',3060,70,'New',12,'perfume1.jpg',3,5,'DTDC',7);

INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (1,1,'MMC');
INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (2,1,'OS');
INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (3,2,'Samsung');
INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (4,2,'Nokia');
INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (5,3,'Perfumes');
INSERT INTO sub_category (SUB_CATEG_ID,CATEG_ID,SUB_CATEG_NAME) VALUES (6,3,'Health Instruments');


INSERT INTO transaction (TRAN_ID,ORDER_ID,ITEM_ID,ITEM_QUANTITY,COURIER,SELLER_ID,SELLER_RATING,TRAN_DATE) VALUES (1,1,1,1,'Professiona','MT2012129',4,'2013-04-04 16:20:09');
INSERT INTO transaction (TRAN_ID,ORDER_ID,ITEM_ID,ITEM_QUANTITY,COURIER,SELLER_ID,SELLER_RATING,TRAN_DATE) VALUES (2,2,1,1,'Professional','MT2012129',3,'2013-04-04 16:20:09');
INSERT INTO transaction (TRAN_ID,ORDER_ID,ITEM_ID,ITEM_QUANTITY,COURIER,SELLER_ID,SELLER_RATING,TRAN_DATE) VALUES (3,3,2,1,'DTDC','MT2012122',4,'2013-04-04 16:20:09');
INSERT INTO transaction (TRAN_ID,ORDER_ID,ITEM_ID,ITEM_QUANTITY,COURIER,SELLER_ID,SELLER_RATING,TRAN_DATE) VALUES (4,6,1,1,'DTDC','MT2012129',NULL,'2013-04-04 19:14:15');
INSERT INTO transaction (TRAN_ID,ORDER_ID,ITEM_ID,ITEM_QUANTITY,COURIER,SELLER_ID,SELLER_RATING,TRAN_DATE) VALUES (5,7,1,1,'DTDC','MT2012129',NULL,'2013-04-04 19:28:56');

INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('admin','admin','','admin','admin@gmail.com','','2013-04-04 17:05:24',NULL,NULL,NULL);
INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('MT2012013','alpna','A','alpna','alpnathakur.29@gmail.com','9986560378','2013-04-04 16:18:35',NULL,NULL,NULL);
INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('MT2012119','Ruchika','A','OM','abc@ab.com','9886276743','2013-04-04 16:21:01',NULL,NULL,NULL);
INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('MT2012122','sravvani','A','peraka','sravaniperaka@gmail.com','9916580494','2013-04-04 16:18:35',NULL,NULL,NULL);
INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('MT2012129','deepthi','A','satya','deepthi.bhagi@gmail.com','9886727257','2013-04-04 16:17:25',NULL,NULL,NULL);
INSERT INTO user (USER_ID,USER_NAME,USER_STATUS,PWD,EMAIL_ID,MOBILE,MEMBER_SINCE,secret_question,secret_answer,dob) VALUES ('MT2012140','sruti davis','A','diamond','sruti.davis@gmail.com','9686518156','2013-04-04 17:24:08','What is your pet name','minnu','1990-03-22');
